/*
 * DIO_Config.h
 *
 *  Created on: Feb 10, 2023
 *      Author: aaa
 */

#ifndef DIO_CONFIG_H_
#define DIO_CONFIG_H_

/*PORTA PINS Directions*/
#define DIO_PORTA_PIN0_INIT_DIR		OUTPUT
#define DIO_PORTA_PIN1_INIT_DIR		OUTPUT
#define DIO_PORTA_PIN2_INIT_DIR		OUTPUT
#define DIO_PORTA_PIN3_INIT_DIR		OUTPUT
#define DIO_PORTA_PIN4_INIT_DIR		OUTPUT
#define DIO_PORTA_PIN5_INIT_DIR		OUTPUT
#define DIO_PORTA_PIN6_INIT_DIR		OUTPUT
#define DIO_PORTA_PIN7_INIT_DIR		OUTPUT

/*PORTB PINS Directions*/
#define DIO_PORTB_PIN0_INIT_DIR		OUTPUT
#define DIO_PORTB_PIN1_INIT_DIR		OUTPUT
#define DIO_PORTB_PIN2_INIT_DIR		OUTPUT
#define DIO_PORTB_PIN3_INIT_DIR		OUTPUT
#define DIO_PORTB_PIN4_INIT_DIR		OUTPUT
#define DIO_PORTB_PIN5_INIT_DIR		OUTPUT
#define DIO_PORTB_PIN6_INIT_DIR		OUTPUT
#define DIO_PORTB_PIN7_INIT_DIR		OUTPUT

/*PORTC PINS Directions*/
#define DIO_PORTC_PIN0_INIT_DIR		OUTPUT
#define DIO_PORTC_PIN1_INIT_DIR		OUTPUT
#define DIO_PORTC_PIN2_INIT_DIR		OUTPUT
#define DIO_PORTC_PIN3_INIT_DIR		OUTPUT
#define DIO_PORTC_PIN4_INIT_DIR		OUTPUT
#define DIO_PORTC_PIN5_INIT_DIR		OUTPUT
#define DIO_PORTC_PIN6_INIT_DIR		OUTPUT
#define DIO_PORTC_PIN7_INIT_DIR		OUTPUT

/*PORTB PINS Directions*/
#define DIO_PORTD_PIN0_INIT_DIR		INPUT  //make it input while using RX
#define DIO_PORTD_PIN1_INIT_DIR		OUTPUT//make it OUTPUT while using TX
#define DIO_PORTD_PIN2_INIT_DIR		OUTPUT
#define DIO_PORTD_PIN3_INIT_DIR		OUTPUT
#define DIO_PORTD_PIN4_INIT_DIR		OUTPUT
#define DIO_PORTD_PIN5_INIT_DIR		OUTPUT
#define DIO_PORTD_PIN6_INIT_DIR		INPUT
#define DIO_PORTD_PIN7_INIT_DIR		OUTPUT

/*PORTA PINS Values*/
#define DIO_PORTA_PIN0_INIT_Val		LOW
#define DIO_PORTA_PIN1_INIT_Val		LOW
#define DIO_PORTA_PIN2_INIT_Val		LOW
#define DIO_PORTA_PIN3_INIT_Val		LOW
#define DIO_PORTA_PIN4_INIT_Val		LOW
#define DIO_PORTA_PIN5_INIT_Val		LOW
#define DIO_PORTA_PIN6_INIT_Val		LOW
#define DIO_PORTA_PIN7_INIT_Val		LOW

/*PORTB PINS Values*/
#define DIO_PORTB_PIN0_INIT_Val		LOW
#define DIO_PORTB_PIN1_INIT_Val		LOW
#define DIO_PORTB_PIN2_INIT_Val		LOW
#define DIO_PORTB_PIN3_INIT_Val		LOW
#define DIO_PORTB_PIN4_INIT_Val		LOW
#define DIO_PORTB_PIN5_INIT_Val		LOW
#define DIO_PORTB_PIN6_INIT_Val		LOW
#define DIO_PORTB_PIN7_INIT_Val		LOW

/*PORTC PINS Values*/
#define DIO_PORTC_PIN0_INIT_Val		LOW
#define DIO_PORTC_PIN1_INIT_Val		LOW
#define DIO_PORTC_PIN2_INIT_Val		LOW
#define DIO_PORTC_PIN3_INIT_Val		LOW
#define DIO_PORTC_PIN4_INIT_Val		LOW
#define DIO_PORTC_PIN5_INIT_Val		LOW
#define DIO_PORTC_PIN6_INIT_Val		LOW
#define DIO_PORTC_PIN7_INIT_Val		LOW

/*PORTD PINS Values*/
#define DIO_PORTD_PIN0_INIT_Val		LOW
#define DIO_PORTD_PIN1_INIT_Val		LOW
#define DIO_PORTD_PIN2_INIT_Val		LOW
#define DIO_PORTD_PIN3_INIT_Val		LOW
#define DIO_PORTD_PIN4_INIT_Val		LOW
#define DIO_PORTD_PIN5_INIT_Val		LOW
#define DIO_PORTD_PIN6_INIT_Val		LOW
#define DIO_PORTD_PIN7_INIT_Val		LOW



#endif /* MCAL_DIO_DIO_CONFIG_H_ */
